@startuml
'https://plantuml.com/class-diagram

header
    Vermittler-Pattern
endheader

footer
    Mark Sudau Consulting & Software
endfooter

together {
    interface Mediator {
        + mediate()
    }

    class KonkreterMediator {
        + mediate()
    }
}

Mediator <|... KonkreterMediator

together {
    interface Kollege

    class EinfacherKollege
    class Komplexerkollege
}
Kollege <|.. EinfacherKollege
Kollege <|.. Komplexerkollege


Mediator <- Kollege

EinfacherKollege <-- KonkreterMediator
Komplexerkollege <-- KonkreterMediator
@enduml
