@startuml
'https://plantuml.com/class-diagram

interface Mediator
class ConcreteMediator implements Mediator {
    # colleague: Colleague
}

abstract class Colleague {
    # mediator: mediator
}
class ConcreteColleague1 extends Colleague
class ConcreteColleague2 extends Colleague

Mediator <- Colleague
ConcreteMediator -> ConcreteColleague1
ConcreteMediator --> ConcreteColleague2
@enduml
